# -*- coding: utf-8 -*-
#This file was originally generated by PyScripter's unitest wizard

import unittest
import EuradinImport.CZAddressLib.MatchTools as mt

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressMatch(self):
        #self.assertEqual(mt.addressMatch("Praha, Mrkvičkova 1270"), True)
        pass

    def testnormalizeAddressString(self):
        self.assertEqual(mt.normalizeAddressString("Karlovy  Vary,  Mrkvičkova  1270"), "Karlovy Vary, Mrkvičkova 1270", "Více mezer je chápáno jako jedna")
        self.assertEqual(mt.normalizeAddressString("Karlovy Vary;Mrkvičkova 1270"), "Karlovy Vary,Mrkvičkova 1270", "Středník je chápán jako oddělovač čárka")
        self.assertEqual(mt.normalizeAddressString("Karlovy Vary:Mrkvičkova 1270"), "Karlovy Vary,Mrkvičkova 1270", "Dvojtečka je chápána jako oddělovač čárka")
        self.assertEqual(mt.normalizeAddressString("Karlovy Vary,,Mrkvičkova 1270"), "Karlovy Vary,Mrkvičkova 1270", "Více čárek je chápáno jako prázdná informace")

        pass


def main():
    unittest.main()

if __name__ == '__main__':
    main()

